name: Filtered
favicon: null
layout_spectrum: 0.3251488406676799
typography_spectrum: 0.5353660515975207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1496451930142939
  lightness: 0.2262979527004063
  saturation: 0.2327302119228989
  rhythmicContrast: 0.9177405999507755
purpose: []
